package com.hust.kien.schoolrecsys.service.vntokenizer;

import lombok.Getter;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.HashSet;
import java.util.Set;

@SuppressWarnings("unchecked")
public class Vocabulary {

    private static Vocabulary instance;
    @Getter
    private Set<String> vnDict;
    @Getter
    private Set<String> countryLNames;
    @Getter
    private Set<String> countrySNames;
    @Getter
    private Set<String> worldCompanies;
    @Getter
    private Set<String> vnLocations;
    @Getter
    private Set<String> vnFirstSentWords;
    @Getter
    private Set<String> vnMiddleNames;
    @Getter
    private Set<String> vnFamilyNames;

    private Vocabulary(String filePath) {
        initVnDict(filePath);
        initCountryL();
        initCountryS();
        initWorldCompany();
        initVnLocation();
        initVnFirstSentWord();
        initVnMiddleName();
        initVnFamilyName();
    }

    public static void init(String filePath) {
        if (filePath == null) {
            throw new IllegalArgumentException("Missing file path");
        }
        if (instance == null)
            instance = new Vocabulary(filePath);
    }

    public static Vocabulary getInstance() {
        if (instance == null) {
            throw new RuntimeException("Not initialized");
        }
        return instance;
    }

    private void initVnDict(String filePath) {
        vnDict = new HashSet<>();
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(filePath));
            vnDict = (Set<String>) ois.readObject();
            ois.close();
        } catch (IOException | ClassNotFoundException e1) {
            e1.printStackTrace();
        }
    }

    private void initCountryL() {
        countryLNames = new HashSet<>();
        countryLNames.add("na uy");
        countryLNames.add("san marino");
        countryLNames.add("phần lan");
        countryLNames.add("bồ đào nha");
        countryLNames.add("ca-ri-bê hà lan");
        countryLNames.add("quần đảo bắc mariana");
        countryLNames.add("ả rập xê-út");
        countryLNames.add("tây ban nha");
        countryLNames.add("quần đảo virgin");
        countryLNames.add("đảo somoa thuộc mỹ");
        countryLNames.add("đông timor");
        countryLNames.add("hoa kỳ");
        countryLNames.add("quần đảo pitcairn");
        countryLNames.add("samoa thuộc mỹ");
        countryLNames.add("hàn quốc");
        countryLNames.add("đảo ascension");
        countryLNames.add("thuỵ sĩ");
        countryLNames.add("ai cập");
        countryLNames.add("burkina faso");
        countryLNames.add("mông cổ");
        countryLNames.add("polynesia thuộc pháp");
        countryLNames.add("turks và caicos");
        countryLNames.add("thổ nhĩ kỳ");
        countryLNames.add("liên bang micronesia");
        countryLNames.add("đảo man");
        countryLNames.add("saint helena");
        countryLNames.add("ả rập saudi");
        countryLNames.add("ba lan");
        countryLNames.add("são tomé và príncipe");
        countryLNames.add("đảo norfolk");
        countryLNames.add("chdcnd triều tiên");
        countryLNames.add("quần đảo canary");
        countryLNames.add("guiana thuộc pháp");
        countryLNames.add("antigua và barbuda");
        countryLNames.add("saint pierre và miquelon");
        countryLNames.add("sri lanka");
        countryLNames.add("ceuta và melilla");
        countryLNames.add("việt nam");
        countryLNames.add("bờ biển ngà");
        countryLNames.add("thuỵ điển");
        countryLNames.add("el salvador");
        countryLNames.add("svalbard và jan mayen");
        countryLNames.add("saint lucia");
        countryLNames.add("diego garcia");
        countryLNames.add("ấn độ");
        countryLNames.add("tây sahara");
        countryLNames.add("quần đảo cook");
        countryLNames.add("guinea xích đạo");
        countryLNames.add("trung quốc");
        countryLNames.add("chdc congo");
        countryLNames.add("cộng hoà dominica");
        countryLNames.add("cape verde");
        countryLNames.add("hà lan");
        countryLNames.add("puerto rico");
        countryLNames.add("đài loan");
        countryLNames.add("cộng hoà séc");
        countryLNames.add("costa rica");
        countryLNames.add("saint kitts và nevis");
        countryLNames.add("nhật bản");
        countryLNames.add("quần đảo faroe");
        countryLNames.add("đan mạch");
        countryLNames.add("turk và caicos");
        countryLNames.add("cabo verde");
        countryLNames.add("nam sudan");
        countryLNames.add("cộng hoà trung phi");
        countryLNames.add("trung phi");
        countryLNames.add("saint vincent và grenadines");
        countryLNames.add("quần đảo cocos");
        countryLNames.add("thành vatican");
        countryLNames.add("saint barthélemy");
        countryLNames.add("nam cực");
        countryLNames.add("trinidad và tobago");
        countryLNames.add("cộng hoà congo");
        countryLNames.add("quần đảo cayman");
        countryLNames.add("saint martin");
        countryLNames.add("tristan da cunha");
        countryLNames.add("bosnia và herzegovina");
        countryLNames.add("thái lan");
        countryLNames.add("new zealand");
        countryLNames.add("hồng kông");
        countryLNames.add("wallis và futuna");
        countryLNames.add("sierra leone");
        countryLNames.add("sint maarten");
        countryLNames.add("quần đảo solomon");
        countryLNames.add("nam phi");
        countryLNames.add("bosna và hercegovina");
        countryLNames.add("vương quốc anh");
        countryLNames.add("papua new guinea");
        countryLNames.add("hy lạp");
        countryLNames.add("đảo giáng sinh");
        countryLNames.add("triều tiên");
        countryLNames.add("quần đảo falkland");
        countryLNames.add("miến điện");
        countryLNames.add("quần đảo marshall");
        countryLNames.add("new caledonia");
    }

    private void initCountryS() {
        countrySNames = new HashSet<>();
        countrySNames.add("mỹ");
        countrySNames.add("belarus");
        countrySNames.add("guinée");
        countrySNames.add("gambia");
        countrySNames.add("cô-oét");
        countrySNames.add("guinea");
        countrySNames.add("estonia");
        countrySNames.add("philippines");
        countrySNames.add("cuba");
        countrySNames.add("mauritius");
        countrySNames.add("mali");
        countrySNames.add("armenia");
        countrySNames.add("aruba");
        countrySNames.add("méxico");
        countrySNames.add("ukraina");
        countrySNames.add("bénin");
        countrySNames.add("congo");
        countrySNames.add("monaco");
        countrySNames.add("séc");
        countrySNames.add("kenya");
        countrySNames.add("hungary");
        countrySNames.add("greenland");
        countrySNames.add("li-băng");
        countrySNames.add("paraguay");
        countrySNames.add("palau");
        countrySNames.add("vanuatu");
        countrySNames.add("colombia");
        countrySNames.add("azerbaijan");
        countrySNames.add("syria");
        countrySNames.add("rwanda");
        countrySNames.add("libya");
        countrySNames.add("guernsey");
        countrySNames.add("afghanistan");
        countrySNames.add("guiné-bissau");
        countrySNames.add("hungari");
        countrySNames.add("kiribati");
        countrySNames.add("dominica");
        countrySNames.add("bulgaria");
        countrySNames.add("brasil");
        countrySNames.add("bahrain");
        countrySNames.add("guatemala");
        countrySNames.add("ghana");
        countrySNames.add("somalia");
        countrySNames.add("jamaica");
        countrySNames.add("togo");
        countrySNames.add("liechtenstein");
        countrySNames.add("serbia");
        countrySNames.add("ma-rốc");
        countrySNames.add("bỉ");
        countrySNames.add("úc");
        countrySNames.add("senegal");
        countrySNames.add("montserrat");
        countrySNames.add("zambia");
        countrySNames.add("namibia");
        countrySNames.add("comoros");
        countrySNames.add("curaçao");
        countrySNames.add("palestine");
        countrySNames.add("canada");
        countrySNames.add("li-bi");
        countrySNames.add("honduras");
        countrySNames.add("réunion");
        countrySNames.add("maldives");
        countrySNames.add("chile");
        countrySNames.add("algérie");
        countrySNames.add("oman");
        countrySNames.add("timor-leste");
        countrySNames.add("brazil");
        countrySNames.add("lesotho");
        countrySNames.add("guyana");
        countrySNames.add("peru");
        countrySNames.add("malaysia");
        countrySNames.add("jersey");
        countrySNames.add("síp");
        countrySNames.add("belize");
        countrySNames.add("nauru");
        countrySNames.add("campuchia");
        countrySNames.add("kuwait");
        countrySNames.add("slovenia");
        countrySNames.add("somali");
        countrySNames.add("haiti");
        countrySNames.add("zimbabwe");
        countrySNames.add("macedonia");
        countrySNames.add("micronesia");
        countrySNames.add("philippin");
        countrySNames.add("bolivia");
        countrySNames.add("brunei");
        countrySNames.add("israel");
        countrySNames.add("lào");
        countrySNames.add("bangladesh");
        countrySNames.add("ý");
        countrySNames.add("ireland");
        countrySNames.add("albania");
        countrySNames.add("botswana");
        countrySNames.add("venezuela");
        countrySNames.add("andorra");
        countrySNames.add("malawi");
        countrySNames.add("moldova");
        countrySNames.add("madagascar");
        countrySNames.add("turkmenistan");
        countrySNames.add("iran");
        countrySNames.add("iraq");
        countrySNames.add("seychelles");
        countrySNames.add("indonesia");
        countrySNames.add("tchad");
        countrySNames.add("nicaragua");
        countrySNames.add("gibraltar");
        countrySNames.add("ethiopia");
        countrySNames.add("ecuador");
        countrySNames.add("guinea-bissau");
        countrySNames.add("mauritania");
        countrySNames.add("albani");
        countrySNames.add("algeria");
        countrySNames.add("mozambique");
        countrySNames.add("cameroon");
        countrySNames.add("vatican");
        countrySNames.add("liban");
        countrySNames.add("panama");
        countrySNames.add("uae");
        countrySNames.add("luxembourg");
        countrySNames.add("nigeria");
        countrySNames.add("sudan");
        countrySNames.add("benin");
        countrySNames.add("chad");
        countrySNames.add("liberia");
        countrySNames.add("djibouti");
        countrySNames.add("đức");
        countrySNames.add("tajikistan");
        countrySNames.add("fiji");
        countrySNames.add("singapore");
        countrySNames.add("mexico");
        countrySNames.add("samoa");
        countrySNames.add("tunisia");
        countrySNames.add("bahamas");
        countrySNames.add("bhutan");
        countrySNames.add("uganda");
        countrySNames.add("uruguay");
        countrySNames.add("gabon");
        countrySNames.add("bungari");
        countrySNames.add("niger");
        countrySNames.add("kyrgyzstan");
        countrySNames.add("pakistan");
        countrySNames.add("martinique");
        countrySNames.add("macao");
        countrySNames.add("kosovo");
        countrySNames.add("mayotte");
        countrySNames.add("yemen");
        countrySNames.add("georgia");
        countrySNames.add("pháp");
        countrySNames.add("ai-len");
        countrySNames.add("argentina");
        countrySNames.add("jordan");
        countrySNames.add("anguilla");
        countrySNames.add("swaziland");
        countrySNames.add("burundi");
        countrySNames.add("slovakia");
        countrySNames.add("uzbekistan");
        countrySNames.add("maroc");
        countrySNames.add("tanzania");
        countrySNames.add("litva");
        countrySNames.add("grenada");
        countrySNames.add("gruzia");
        countrySNames.add("lít-va");
        countrySNames.add("guam");
        countrySNames.add("eritrea");
        countrySNames.add("áo");
        countrySNames.add("croatia");
        countrySNames.add("niue");
        countrySNames.add("nepal");
        countrySNames.add("tokelau");
        countrySNames.add("bermuda");
        countrySNames.add("i-rắc");
        countrySNames.add("suriname");
        countrySNames.add("guadeloupe");
        countrySNames.add("nga");
        countrySNames.add("romania");
        countrySNames.add("angola");
        countrySNames.add("latvia");
        countrySNames.add("kazakhstan");
        countrySNames.add("malta");
        countrySNames.add("myanmar");
        countrySNames.add("iceland");
        countrySNames.add("românia");
        countrySNames.add("montenegro");
        countrySNames.add("macau");
        countrySNames.add("tuvalu");
        countrySNames.add("qatar");
        countrySNames.add("tonga");
        countrySNames.add("barbados");
    }

    private void initWorldCompany() {
        worldCompanies = new HashSet<>();
        worldCompanies.add("verizon");
        worldCompanies.add("prada");
        worldCompanies.add("hp");
        worldCompanies.add("walmart");
        worldCompanies.add("adidas");
        worldCompanies.add("mastercard");
        worldCompanies.add("digg");
        worldCompanies.add("canon");
        worldCompanies.add("ikea");
        worldCompanies.add("sony");
        worldCompanies.add("twitter");
        worldCompanies.add("lego");
        worldCompanies.add("toshiba");
        worldCompanies.add("nokia");
        worldCompanies.add("bbc");
        worldCompanies.add("vmware");
        worldCompanies.add("mercedes-benz");
        worldCompanies.add("google");
        worldCompanies.add("intel");
        worldCompanies.add("iphone");
        worldCompanies.add("rbc");
        worldCompanies.add("fedex");
        worldCompanies.add("mercedes");
        worldCompanies.add("gillette");
        worldCompanies.add("ups");
        worldCompanies.add("carrefour");
        worldCompanies.add("lenovo");
        worldCompanies.add("loreal");
        worldCompanies.add("mcdonald");
        worldCompanies.add("coca-cola");
        worldCompanies.add("guardian");
        worldCompanies.add("cisco");
        worldCompanies.add("paypal");
        worldCompanies.add("cvs");
        worldCompanies.add("acer");
        worldCompanies.add("cnn");
        worldCompanies.add("nike");
        worldCompanies.add("facebook");
        worldCompanies.add("spotify");
        worldCompanies.add("adobe");
        worldCompanies.add("kfc");
        worldCompanies.add("westpac");
        worldCompanies.add("subway");
        worldCompanies.add("ibm");
        worldCompanies.add("panasonic");
        worldCompanies.add("visa");
        worldCompanies.add("motorola");
        worldCompanies.add("nissan");
        worldCompanies.add("citibank");
        worldCompanies.add("baidu");
        worldCompanies.add("ford");
        worldCompanies.add("microsoft");
        worldCompanies.add("bmw");
        worldCompanies.add("foxconn");
        worldCompanies.add("yahoo");
        worldCompanies.add("hermes");
        worldCompanies.add("oracle");
        worldCompanies.add("mcdonalds");
        worldCompanies.add("tencent");
        worldCompanies.add("mtv");
        worldCompanies.add("zara");
        worldCompanies.add("amazon");
        worldCompanies.add("toyota");
        worldCompanies.add("gucci");
        worldCompanies.add("ebay");
        worldCompanies.add("kodak");
        worldCompanies.add("youtube");
        worldCompanies.add("android");
        worldCompanies.add("linkedin");
        worldCompanies.add("myspace");
        worldCompanies.add("t-mobile");
        worldCompanies.add("apple");
        worldCompanies.add("samsung");
        worldCompanies.add("aldi");
        worldCompanies.add("colgate");
        worldCompanies.add("starbucks");
        worldCompanies.add("pepsi");
        worldCompanies.add("honda");
        worldCompanies.add("dell");
        worldCompanies.add("hitachi");
        worldCompanies.add("blackberry");
        worldCompanies.add("disney");
        worldCompanies.add("siemens");
        worldCompanies.add("vodafone");
    }

    private void initVnLocation() {
        vnLocations = new HashSet<>();
        vnLocations.add("mỹ tho");
        vnLocations.add("nam đông");
        vnLocations.add("kiên lương");
        vnLocations.add("lương sơn");
        vnLocations.add("gò vấp");
        vnLocations.add("quang bình");
        vnLocations.add("ia pa");
        vnLocations.add("lạc sơn");
        vnLocations.add("chí linh");
        vnLocations.add("ninh hải");
        vnLocations.add("sơn dương");
        vnLocations.add("quan sơn");
        vnLocations.add("ứng hoà");
        vnLocations.add("krông pắk");
        vnLocations.add("tân hưng");
        vnLocations.add("nghệ an");
        vnLocations.add("tân thạnh");
        vnLocations.add("yên định");
        vnLocations.add("mường nhé");
        vnLocations.add("ngô quyền");
        vnLocations.add("hàm thuận bắc");
        vnLocations.add("phú tân");
        vnLocations.add("tân hồng");
        vnLocations.add("trà ôn");
        vnLocations.add("từ liêm");
        vnLocations.add("bình thuận");
        vnLocations.add("an phú");
        vnLocations.add("duy xuyên");
        vnLocations.add("nam trực");
        vnLocations.add("phù cừ");
        vnLocations.add("mai sơn");
        vnLocations.add("thạnh phú");
        vnLocations.add("lộc bình");
        vnLocations.add("kim thành");
        vnLocations.add("cái bè");
        vnLocations.add("hà quảng");
        vnLocations.add("long thành");
        vnLocations.add("đồng phù");
        vnLocations.add("bảo yên");
        vnLocations.add("chiêm hoá");
        vnLocations.add("gia nghĩa");
        vnLocations.add("an dương");
        vnLocations.add("phú quý");
        vnLocations.add("quảng trạch");
        vnLocations.add("trường sa");
        vnLocations.add("hoàn kiếm");
        vnLocations.add("thủ thừa");
        vnLocations.add("hải lăng");
        vnLocations.add("pleiku");
        vnLocations.add("thanh hoá");
        vnLocations.add("bạch thông");
        vnLocations.add("vĩnh phúc");
        vnLocations.add("vãn lãng");
        vnLocations.add("bình gia");
        vnLocations.add("sa thầy");
        vnLocations.add("triệu sơn");
        vnLocations.add("yên thuỷ");
        vnLocations.add("văn giang");
        vnLocations.add("hồ chí minh");
        vnLocations.add("nga sơn");
        vnLocations.add("gia lâm");
        vnLocations.add("vị thanh");
        vnLocations.add("cái răng");
        vnLocations.add("cao bằng");
        vnLocations.add("hoài ân");
        vnLocations.add("vĩnh long");
        vnLocations.add("kim động");
        vnLocations.add("ngân sơn");
        vnLocations.add("lấp vò");
        vnLocations.add("sông công");
        vnLocations.add("hoài nhơn");
        vnLocations.add("kim bôi");
        vnLocations.add("bắc ninh");
        vnLocations.add("thái nguyên");
        vnLocations.add("đơn dương");
        vnLocations.add("định quán");
        vnLocations.add("gò công");
        vnLocations.add("hà giang");
        vnLocations.add("hoà bình");
        vnLocations.add("mèo vạc");
        vnLocations.add("mộc châu");
        vnLocations.add("quảng ngãi");
        vnLocations.add("cẩm giàng");
        vnLocations.add("sông hinh");
        vnLocations.add("thới bình");
        vnLocations.add("phụng hiệp");
        vnLocations.add("ninh hoà");
        vnLocations.add("hậu giang");
        vnLocations.add("cái nước");
        vnLocations.add("ô môn");
        vnLocations.add("gia lai");
        vnLocations.add("phổ yên");
        vnLocations.add("quế sơn");
        vnLocations.add("yên thành");
        vnLocations.add("tiên du");
        vnLocations.add("an minh");
        vnLocations.add("chợ lách");
        vnLocations.add("phú ninh");
        vnLocations.add("tủa chùa");
        vnLocations.add("hương trà");
        vnLocations.add("thăng bình");
        vnLocations.add("vĩnh thuận");
        vnLocations.add("hà tĩnh");
        vnLocations.add("lâm đồng");
        vnLocations.add("phú quốc");
        vnLocations.add("long mỹ");
        vnLocations.add("long an");
        vnLocations.add("bình lục");
        vnLocations.add("vĩnh thạnh");
        vnLocations.add("đống đa");
        vnLocations.add("hạ long");
        vnLocations.add("kỳ sơn");
        vnLocations.add("đăk song");
        vnLocations.add("lai vung");
        vnLocations.add("ý yên");
        vnLocations.add("xuyên mộc");
        vnLocations.add("vị xuyên");
        vnLocations.add("duy tiên");
        vnLocations.add("khánh sơn");
        vnLocations.add("bỉm sơn");
        vnLocations.add("hiệp đức");
        vnLocations.add("kim sơn");
        vnLocations.add("xín mần");
        vnLocations.add("hương thuỷ");
        vnLocations.add("tuy hoà");
        vnLocations.add("u minh");
        vnLocations.add("thiệu hoá");
        vnLocations.add("bù đốp");
        vnLocations.add("yên sơn");
        vnLocations.add("quảng xương");
        vnLocations.add("cần đước");
        vnLocations.add("thuỷ nguyên");
        vnLocations.add("yên dũng");
        vnLocations.add("yên hưng");
        vnLocations.add("bắc mê");
        vnLocations.add("thọ xuân");
        vnLocations.add("móng cái");
        vnLocations.add("lạc dương");
        vnLocations.add("cẩm xuyên");
        vnLocations.add("lâm thao");
        vnLocations.add("bình tân");
        vnLocations.add("phúc yên");
        vnLocations.add("sơn tây");
        vnLocations.add("vĩnh châu");
        vnLocations.add("na hang");
        vnLocations.add("chương mỹ");
        vnLocations.add("bảo lộc");
        vnLocations.add("nghi xuân");
        vnLocations.add("lương tài");
        vnLocations.add("thoại sơn");
        vnLocations.add("cửa lò");
        vnLocations.add("đông hưng");
        vnLocations.add("lập thạch");
        vnLocations.add("nam định");
        vnLocations.add("quảng nam");
        vnLocations.add("kiên hải");
        vnLocations.add("đồng xuân");
        vnLocations.add("phú xuyên");
        vnLocations.add("tiểu cần");
        vnLocations.add("phúc thọ");
        vnLocations.add("đông giang");
        vnLocations.add("gò dầu");
        vnLocations.add("giá rai");
        vnLocations.add("tây sơn");
        vnLocations.add("phú hoà");
        vnLocations.add("việt yên");
        vnLocations.add("đak đoa");
        vnLocations.add("mường la");
        vnLocations.add("hồng ngự");
        vnLocations.add("bắc bình");
        vnLocations.add("phủ lý");
        vnLocations.add("gio linh");
        vnLocations.add("cồn cỏ");
        vnLocations.add("đức linh");
        vnLocations.add("củ chi");
        vnLocations.add("hương sơn");
        vnLocations.add("tịnh biên");
        vnLocations.add("bình thuỷ");
        vnLocations.add("nhà bè");
        vnLocations.add("yên thế");
        vnLocations.add("vĩnh tường");
        vnLocations.add("kế sách");
        vnLocations.add("sóc sơn");
        vnLocations.add("chợ đồn");
        vnLocations.add("châu phú");
        vnLocations.add("kiến an");
        vnLocations.add("sốp cộp");
        vnLocations.add("lệ thuỷ");
        vnLocations.add("sơn tịnh");
        vnLocations.add("càng long");
        vnLocations.add("vị thuỷ");
        vnLocations.add("ea súp");
        vnLocations.add("quảng điền");
        vnLocations.add("nghĩa lộ");
        vnLocations.add("đồ sơn");
        vnLocations.add("krông pa");
        vnLocations.add("việt trì");
        vnLocations.add("tân thành");
        vnLocations.add("nghĩa hưng");
        vnLocations.add("bạc liêu");
        vnLocations.add("hưng yên");
        vnLocations.add("hoàng mai");
        vnLocations.add("diên khánh");
        vnLocations.add("lăk");
        vnLocations.add("bắc trà my");
        vnLocations.add("tân châu");
        vnLocations.add("tân phú");
        vnLocations.add("bình long");
        vnLocations.add("đông hà");
        vnLocations.add("kon plông");
        vnLocations.add("sa đéc");
        vnLocations.add("an lão");
        vnLocations.add("như xuân");
        vnLocations.add("bến lức");
        vnLocations.add("thanh khê");
        vnLocations.add("long xuyên");
        vnLocations.add("chợ gạo");
        vnLocations.add("lục nam");
        vnLocations.add("hoà thành");
        vnLocations.add("vũng liêm");
        vnLocations.add("bình định");
        vnLocations.add("cẩm mỹ");
        vnLocations.add("mộc hoá");
        vnLocations.add("tánh linh");
        vnLocations.add("đất đỏ");
        vnLocations.add("quế võ");
        vnLocations.add("trấn yên");
        vnLocations.add("cầu ngang");
        vnLocations.add("lai châu");
        vnLocations.add("gò công tây");
        vnLocations.add("lý nhân");
        vnLocations.add("bà rịa-vũng tàu");
        vnLocations.add("bình giang");
        vnLocations.add("mường khương");
        vnLocations.add("gò quao");
        vnLocations.add("bình đại");
        vnLocations.add("điện bàn");
        vnLocations.add("hải châu");
        vnLocations.add("bắc giang");
        vnLocations.add("văn lâm");
        vnLocations.add("ninh thuận");
        vnLocations.add("cô tô");
        vnLocations.add("quảng uyên");
        vnLocations.add("đông hải");
        vnLocations.add("phan thiết");
        vnLocations.add("tĩnh gia");
        vnLocations.add("bạch long vĩ");
        vnLocations.add("hoài đức");
        vnLocations.add("la gi");
        vnLocations.add("ngọc hồi");
        vnLocations.add("bình sơn");
        vnLocations.add("dương minh châu");
        vnLocations.add("can lộc");
        vnLocations.add("hồng bàng");
        vnLocations.add("thanh miện");
        vnLocations.add("trảng bàng");
        vnLocations.add("thái bình");
        vnLocations.add("hải dương");
        vnLocations.add("hà tây");
        vnLocations.add("krông nô");
        vnLocations.add("tam đường");
        vnLocations.add("nguyên bình");
        vnLocations.add("thủ dầu một");
        vnLocations.add("vĩnh lộc");
        vnLocations.add("đăk r'lấp");
        vnLocations.add("hai bà trưng");
        vnLocations.add("long khánh");
        vnLocations.add("bình liêu");
        vnLocations.add("đồng hỷ");
        vnLocations.add("võ nhai");
        vnLocations.add("lạc thuỷ");
        vnLocations.add("quỳnh phụ");
        vnLocations.add("diễn châu");
        vnLocations.add("cầu giấy");
        vnLocations.add("sơn la");
        vnLocations.add("sông mã");
        vnLocations.add("kinh môn");
        vnLocations.add("thạch thành");
        vnLocations.add("ea kar");
        vnLocations.add("krông búk");
        vnLocations.add("gò công đông");
        vnLocations.add("phù ninh");
        vnLocations.add("sơn hà");
        vnLocations.add("đạ tẻh");
        vnLocations.add("mộ đức");
        vnLocations.add("cờ đỏ");
        vnLocations.add("hương khê");
        vnLocations.add("phú lương");
        vnLocations.add("di linh");
        vnLocations.add("phú vang");
        vnLocations.add("lạng giang");
        vnLocations.add("yên mô");
        vnLocations.add("giao thuỷ");
        vnLocations.add("quốc oai");
        vnLocations.add("tuyên quang");
        vnLocations.add("bát xát");
        vnLocations.add("bắc hà");
        vnLocations.add("đắk lắk");
        vnLocations.add("tiên phước");
        vnLocations.add("lê chân");
        vnLocations.add("tiên yên");
        vnLocations.add("bến cát");
        vnLocations.add("tây giang");
        vnLocations.add("đà nẵng");
        vnLocations.add("ia grai");
        vnLocations.add("tam bình");
        vnLocations.add("thường tín");
        vnLocations.add("vĩnh bảo");
        vnLocations.add("hướng hoá");
        vnLocations.add("sơn trà");
        vnLocations.add("tân uyên");
        vnLocations.add("m'đrăk");
        vnLocations.add("quản bạ");
        vnLocations.add("liên chiểu");
        vnLocations.add("tri tôn");
        vnLocations.add("tiên lãng");
        vnLocations.add("biên hoà");
        vnLocations.add("hải hậu");
        vnLocations.add("tây ninh");
        vnLocations.add("quỳnh nhai");
        vnLocations.add("thạch hà");
        vnLocations.add("đồng nai");
        vnLocations.add("tuyên hoá");
        vnLocations.add("mai châu");
        vnLocations.add("yên bái");
        vnLocations.add("duyên hải");
        vnLocations.add("tháp mười");
        vnLocations.add("phú nhuận");
        vnLocations.add("ân thi");
        vnLocations.add("khoái châu");
        vnLocations.add("hòn đất");
        vnLocations.add("thống nhất");
        vnLocations.add("nghĩa đàn");
        vnLocations.add("quế phong");
        vnLocations.add("thủ đức");
        vnLocations.add("hạ lang");
        vnLocations.add("vĩnh linh");
        vnLocations.add("yên lạc");
        vnLocations.add("triệu phong");
        vnLocations.add("lâm hà");
        vnLocations.add("bảo lâm");
        vnLocations.add("hải phòng");
        vnLocations.add("vũ quang");
        vnLocations.add("cao lộc");
        vnLocations.add("nhơn trạch");
        vnLocations.add("quảng trị");
        vnLocations.add("thạch thất");
        vnLocations.add("chơn thành");
        vnLocations.add("tân yên");
        vnLocations.add("thanh hà");
        vnLocations.add("thạnh hoá");
        vnLocations.add("si ma cai");
        vnLocations.add("bác ái");
        vnLocations.add("đăk hà");
        vnLocations.add("yên minh");
        vnLocations.add("tân bình");
        vnLocations.add("đại từ");
        vnLocations.add("phục hoà");
        vnLocations.add("ninh sơn");
        vnLocations.add("long phú");
        vnLocations.add("hà tiên");
        vnLocations.add("thanh bình");
        vnLocations.add("mỏ cày");
        vnLocations.add("thạnh trị");
        vnLocations.add("trà vinh");
        vnLocations.add("dầu tiếng");
        vnLocations.add("bắc kạn");
        vnLocations.add("chư sê");
        vnLocations.add("thanh trì");
        vnLocations.add("ngọc lạc");
        vnLocations.add("từ sơn");
        vnLocations.add("gia bình");
        vnLocations.add("pác nặm");
        vnLocations.add("thốt nốt");
        vnLocations.add("trà bồng");
        vnLocations.add("thừa thiên-huế");
        vnLocations.add("phước long");
        vnLocations.add("cẩm phả");
        vnLocations.add("kon rẫy");
        vnLocations.add("long biên");
        vnLocations.add("cư m'gar");
        vnLocations.add("cao lãnh");
        vnLocations.add("buôn đôn");
        vnLocations.add("đắk nông");
        vnLocations.add("lý sơn");
        vnLocations.add("sóc trăng");
        vnLocations.add("hoằng hoá");
        vnLocations.add("quận 10");
        vnLocations.add("krông ana");
        vnLocations.add("quận 11");
        vnLocations.add("quận 12");
        vnLocations.add("phan rang-tháp chàm");
        vnLocations.add("tân kỳ");
        vnLocations.add("tương dương");
        vnLocations.add("đan phượng");
        vnLocations.add("anh sơn");
        vnLocations.add("quận 2");
        vnLocations.add("quận 1");
        vnLocations.add("qui nhơn");
        vnLocations.add("tư nghĩa");
        vnLocations.add("bố trạch");
        vnLocations.add("quận 9");
        vnLocations.add("thạch an");
        vnLocations.add("bảo thắng");
        vnLocations.add("quận 8");
        vnLocations.add("quận 7");
        vnLocations.add("nghĩa hành");
        vnLocations.add("quận 6");
        vnLocations.add("quận 5");
        vnLocations.add("hội an");
        vnLocations.add("quận 4");
        vnLocations.add("quận 3");
        vnLocations.add("phong điền");
        vnLocations.add("xuân lộc");
        vnLocations.add("côn đảo");
        vnLocations.add("nha trang");
        vnLocations.add("tân lạc");
        vnLocations.add("hạ hoà");
        vnLocations.add("gia viễn");
        vnLocations.add("đồng tháp");
        vnLocations.add("hoành bồ");
        vnLocations.add("bắc quang");
        vnLocations.add("na rì");
        vnLocations.add("sông cầu");
        vnLocations.add("mường tè");
        vnLocations.add("yên phong");
        vnLocations.add("tứ kỳ");
        vnLocations.add("vũ thư");
        vnLocations.add("mỹ hào");
        vnLocations.add("chư prông");
        vnLocations.add("hóc môn");
        vnLocations.add("châu đốc");
        vnLocations.add("đô lương");
        vnLocations.add("mang thít");
        vnLocations.add("tràng định");
        vnLocations.add("cam ranh");
        vnLocations.add("mang yang");
        vnLocations.add("hàm thuận nam");
        vnLocations.add("hưng nguyên");
        vnLocations.add("kiến xương");
        vnLocations.add("ninh phước");
        vnLocations.add("phong thổ");
        vnLocations.add("đức thọ");
        vnLocations.add("hồng lĩnh");
        vnLocations.add("khánh vĩnh");
        vnLocations.add("mỹ lộc");
        vnLocations.add("ngọc hiển");
        vnLocations.add("phước sơn");
        vnLocations.add("hà đông");
        vnLocations.add("lào cai");
        vnLocations.add("vĩnh yên");
        vnLocations.add("quỳ châu");
        vnLocations.add("sơn động");
        vnLocations.add("bến cầu");
        vnLocations.add("đông anh");
        vnLocations.add("kông chro");
        vnLocations.add("trảng bom");
        vnLocations.add("đông triều");
        vnLocations.add("ba tơ");
        vnLocations.add("cù lao dung");
        vnLocations.add("mỹ xuyên");
        vnLocations.add("quảng hà");
        vnLocations.add("tân biên");
        vnLocations.add("bá thước");
        vnLocations.add("cà mau");
        vnLocations.add("chi lăng");
        vnLocations.add("yên bình");
        vnLocations.add("bình minh");
        vnLocations.add("bình dương");
        vnLocations.add("an nhơn");
        vnLocations.add("chư păh");
        vnLocations.add("việt nam");
        vnLocations.add("giồng riềng");
        vnLocations.add("cát tiên");
        vnLocations.add("thuận an");
        vnLocations.add("ngã năm");
        vnLocations.add("cẩm thuỷ");
        vnLocations.add("minh long");
        vnLocations.add("nam đàn");
        vnLocations.add("tân hiệp");
        vnLocations.add("thanh sơn");
        vnLocations.add("dĩ an");
        vnLocations.add("thuận thành");
        vnLocations.add("điện biên phủ");
        vnLocations.add("vạn ninh");
        vnLocations.add("hưng yê");
        vnLocations.add("thái thuỵ");
        vnLocations.add("thanh xuân");
        vnLocations.add("cần giờ");
        vnLocations.add("ngũ hành sơn");
        vnLocations.add("ba tri");
        vnLocations.add("hồng dân");
        vnLocations.add("ninh giang");
        vnLocations.add("phan rang tháp chàm");
        vnLocations.add("than uyên");
        vnLocations.add("phú lộc");
        vnLocations.add("thanh chương");
        vnLocations.add("lục ngạn");
        vnLocations.add("năm căn");
        vnLocations.add("điện biên đông");
        vnLocations.add("hữu lũng");
        vnLocations.add("hoàng su phì");
        vnLocations.add("tây hồ");
        vnLocations.add("bắc yên");
        vnLocations.add("sài gòn");
        vnLocations.add("vĩnh cửu");
        vnLocations.add("bình phước");
        vnLocations.add("nam sách");
        vnLocations.add("hưng hà");
        vnLocations.add("bình chánh");
        vnLocations.add("uông bí");
        vnLocations.add("ea h'leo");
        vnLocations.add("tam điệp");
        vnLocations.add("nam giang");
        vnLocations.add("trùng khánh");
        vnLocations.add("gia lộc");
        vnLocations.add("tam dương");
        vnLocations.add("hoà an");
        vnLocations.add("thừa thiên huế");
        vnLocations.add("nông cống");
        vnLocations.add("tam kỳ");
        vnLocations.add("đak pơ");
        vnLocations.add("bình thạnh");
        vnLocations.add("hà nội");
        vnLocations.add("châu thành");
        vnLocations.add("tiên lữ");
        vnLocations.add("cầu kè");
        vnLocations.add("ninh kiều");
        vnLocations.add("buôn ma thuột");
        vnLocations.add("an khê");
        vnLocations.add("đức huệ");
        vnLocations.add("tiền hải");
        vnLocations.add("tuy phước");
        vnLocations.add("bà rịa");
        vnLocations.add("đa krông");
        vnLocations.add("đồng xoài");
        vnLocations.add("ba vì");
        vnLocations.add("quảng ninh");
        vnLocations.add("điện biên");
        vnLocations.add("hà trung");
        vnLocations.add("thanh oai");
        vnLocations.add("trà cú");
        vnLocations.add("văn yên");
        vnLocations.add("bình xuyên");
        vnLocations.add("hoà vang");
        vnLocations.add("trà lĩnh");
        vnLocations.add("yên khánh");
        vnLocations.add("kbang");
        vnLocations.add("hoàng sa");
        vnLocations.add("văn quan");
        vnLocations.add("ba chẽ");
        vnLocations.add("nho quan");
        vnLocations.add("khánh hoà");
        vnLocations.add("đăk mil");
        vnLocations.add("kiến thuỵ");
        vnLocations.add("đầm hà");
        vnLocations.add("hàm tân");
        vnLocations.add("phù cát");
        vnLocations.add("kim bảng");
        vnLocations.add("vũng tầu");
        vnLocations.add("kiên giang");
        vnLocations.add("long hồ");
        vnLocations.add("mường chà");
        vnLocations.add("thanh ba");
        vnLocations.add("đại lộc");
        vnLocations.add("mê linh");
        vnLocations.add("mường lát");
        vnLocations.add("đạ huoai");
        vnLocations.add("huế");
        vnLocations.add("cần thơ");
        vnLocations.add("vụ bản");
        vnLocations.add("thanh liêm");
        vnLocations.add("đoan hùng");
        vnLocations.add("hiệp hoà");
        vnLocations.add("bắc sơn");
        vnLocations.add("tân trụ");
        vnLocations.add("cần giuộc");
        vnLocations.add("đăk glong");
        vnLocations.add("hậu lộc");
        vnLocations.add("kỳ anh");
        vnLocations.add("cai lậy");
        vnLocations.add("krông bông");
        vnLocations.add("yên lập");
        vnLocations.add("mù căng chải");
        vnLocations.add("mỹ tú");
        vnLocations.add("trạm tấu");
        vnLocations.add("cư jút");
        vnLocations.add("quỳ hợp");
        vnLocations.add("tân phước");
        vnLocations.add("vĩnh lợi");
        vnLocations.add("đồng văn");
        vnLocations.add("đông sơn");
        vnLocations.add("tây trà");
        vnLocations.add("lộc ninh");
        vnLocations.add("sầm sơn");
        vnLocations.add("lạng sơn");
        vnLocations.add("sa pa");
        vnLocations.add("hàm yên");
        vnLocations.add("vân đồn");
        vnLocations.add("đà bắc");
        vnLocations.add("vân canh");
        vnLocations.add("sơn hoà");
        vnLocations.add("thuận bắc");
        vnLocations.add("châu đức");
        vnLocations.add("thường xuân");
        vnLocations.add("định hoá");
        vnLocations.add("giồng trôm");
        vnLocations.add("núi thành");
        vnLocations.add("rạch giá");
        vnLocations.add("con cuông");
        vnLocations.add("ninh bình");
        vnLocations.add("đồng hới");
        vnLocations.add("tân an");
        vnLocations.add("trực ninh");
        vnLocations.add("thuận châu");
        vnLocations.add("vinh");
        vnLocations.add("trần văn thời");
        vnLocations.add("minh hoá");
        vnLocations.add("yên mỹ");
        vnLocations.add("quan hoá");
        vnLocations.add("văn bàn");
        vnLocations.add("cam lộ");
        vnLocations.add("lang chánh");
        vnLocations.add("phù yên");
        vnLocations.add("đăk tô");
        vnLocations.add("hoa lư");
        vnLocations.add("lục yên");
        vnLocations.add("đức phổ");
        vnLocations.add("hà nam");
        vnLocations.add("tuy an");
        vnLocations.add("an giang");
        vnLocations.add("ba bể");
        vnLocations.add("xuân trường");
        vnLocations.add("cát hải");
        vnLocations.add("kon tum");
        vnLocations.add("bù đăng");
        vnLocations.add("krông năng");
        vnLocations.add("an biên");
        vnLocations.add("yên châu");
        vnLocations.add("phú thọ");
        vnLocations.add("tam nông");
        vnLocations.add("quỳnh lưu");
        vnLocations.add("đình lập");
        vnLocations.add("nghi lộc");
        vnLocations.add("chợ mới");
        vnLocations.add("đức trọng");
        vnLocations.add("đầm dơi");
        vnLocations.add("long đất");
        vnLocations.add("mường lay");
        vnLocations.add("tiền giang");
        vnLocations.add("thông nông");
        vnLocations.add("phú yên");
        vnLocations.add("quảng bình");
        vnLocations.add("sìn hồ");
        vnLocations.add("tuy phong");
        vnLocations.add("ba đình");
        vnLocations.add("phù mỹ");
        vnLocations.add("đức hoà");
        vnLocations.add("bảo lạc");
        vnLocations.add("đăk glei");
        vnLocations.add("bến tre");
        vnLocations.add("như thanh");
        vnLocations.add("thanh thuỷ");
        vnLocations.add("đà lạt");
        vnLocations.add("đức cơ");
        vnLocations.add("văn chấn");
        vnLocations.add("bà rịa vũng tàu");
        vnLocations.add("vĩnh hưng");
        vnLocations.add("cao phong");
        vnLocations.add("nam trà my");
        vnLocations.add("phú giáo");
        vnLocations.add("phú bình");
        vnLocations.add("ayun pa");
        vnLocations.add("mỹ đức");
        vnLocations.add("tuần giáo");
    }

    private void initVnFirstSentWord() {
        vnFirstSentWords = new HashSet<>();
        vnFirstSentWords.add("được");
        vnFirstSentWords.add("cty");
        vnFirstSentWords.add("mẹ");
        vnFirstSentWords.add("trừ");
        vnFirstSentWords.add("lên");
        vnFirstSentWords.add("trưởng");
        vnFirstSentWords.add("là");
        vnFirstSentWords.add("chàng");
        vnFirstSentWords.add("theo");
        vnFirstSentWords.add("tên");
        vnFirstSentWords.add("giờ");
        vnFirstSentWords.add("biết");
        vnFirstSentWords.add("già");
        vnFirstSentWords.add("những");
        vnFirstSentWords.add("thấy");
        vnFirstSentWords.add("thương");
        vnFirstSentWords.add("lang");
        vnFirstSentWords.add("gái");
        vnFirstSentWords.add("mà");
        vnFirstSentWords.add("xóm");
        vnFirstSentWords.add("má");
        vnFirstSentWords.add("cầu");
        vnFirstSentWords.add("khách");
        vnFirstSentWords.add("nhánh");
        vnFirstSentWords.add("hôm");
        vnFirstSentWords.add("nhớ");
        vnFirstSentWords.add("hạng");
        vnFirstSentWords.add("huyện");
        vnFirstSentWords.add("vậy");
        vnFirstSentWords.add("nhà");
        vnFirstSentWords.add("ấp");
        vnFirstSentWords.add("sông");
        vnFirstSentWords.add("thằng");
        vnFirstSentWords.add("nài");
        vnFirstSentWords.add("ngành");
        vnFirstSentWords.add("nếu");
        vnFirstSentWords.add("trời");
        vnFirstSentWords.add("đảng");
        vnFirstSentWords.add("vào");
        vnFirstSentWords.add("thầy");
        vnFirstSentWords.add("hai");
        vnFirstSentWords.add("vùng");
        vnFirstSentWords.add("chuyện");
        vnFirstSentWords.add("nhìn");
        vnFirstSentWords.add("tim");
        vnFirstSentWords.add("cha");
        vnFirstSentWords.add("sang");
        vnFirstSentWords.add("bên");
        vnFirstSentWords.add("đường");
        vnFirstSentWords.add("cho");
        vnFirstSentWords.add("bảng");
        vnFirstSentWords.add("khi");
        vnFirstSentWords.add("quận");
        vnFirstSentWords.add("biển");
        vnFirstSentWords.add("cu");
        vnFirstSentWords.add("metro");
        vnFirstSentWords.add("vốn");
        vnFirstSentWords.add("đến");
        vnFirstSentWords.add("năm");
        vnFirstSentWords.add("khu");
        vnFirstSentWords.add("đài");
        vnFirstSentWords.add("miền");
        vnFirstSentWords.add("việc");
        vnFirstSentWords.add("do");
        vnFirstSentWords.add("lập");
        vnFirstSentWords.add("nghe");
        vnFirstSentWords.add("mắt");
        vnFirstSentWords.add("viện");
        vnFirstSentWords.add("cả");
        vnFirstSentWords.add("em");
        vnFirstSentWords.add("rừng");
        vnFirstSentWords.add("liệu");
        vnFirstSentWords.add("bố");
        vnFirstSentWords.add("bộ");
        vnFirstSentWords.add("cháu");
        vnFirstSentWords.add("riêng");
        vnFirstSentWords.add("bà");
        vnFirstSentWords.add("số");
        vnFirstSentWords.add("chị");
        vnFirstSentWords.add("người");
        vnFirstSentWords.add("bé");
        vnFirstSentWords.add("tàu");
        vnFirstSentWords.add("làng");
        vnFirstSentWords.add("cảng");
        vnFirstSentWords.add("sở");
        vnFirstSentWords.add("chiếc");
        vnFirstSentWords.add("tết");
        vnFirstSentWords.add("cậu");
        vnFirstSentWords.add("luật");
        vnFirstSentWords.add("chờ");
        vnFirstSentWords.add("rời");
        vnFirstSentWords.add("chắc");
        vnFirstSentWords.add("hội");
        vnFirstSentWords.add("chợ");
        vnFirstSentWords.add("viên");
        vnFirstSentWords.add("cụ");
        vnFirstSentWords.add("nay");
        vnFirstSentWords.add("thuốc");
        vnFirstSentWords.add("bọn");
        vnFirstSentWords.add("tờ");
        vnFirstSentWords.add("phía");
        vnFirstSentWords.add("chữ");
        vnFirstSentWords.add("xe");
        vnFirstSentWords.add("cò");
        vnFirstSentWords.add("có");
        vnFirstSentWords.add("cô");
        vnFirstSentWords.add("dân");
        vnFirstSentWords.add("nhóm");
        vnFirstSentWords.add("song");
        vnFirstSentWords.add("chú");
        vnFirstSentWords.add("từ");
        vnFirstSentWords.add("như");
        vnFirstSentWords.add("ngày");
        vnFirstSentWords.add("phim");
        vnFirstSentWords.add("chính");
        vnFirstSentWords.add("tân");
        vnFirstSentWords.add("gặp");
        vnFirstSentWords.add("các");
        vnFirstSentWords.add("quê");
        vnFirstSentWords.add("dì");
        vnFirstSentWords.add("bởi");
        vnFirstSentWords.add("quí");
        vnFirstSentWords.add("về");
        vnFirstSentWords.add("trại");
        vnFirstSentWords.add("tại");
        vnFirstSentWords.add("lão");
        vnFirstSentWords.add("đảo");
        vnFirstSentWords.add("nguyên");
        vnFirstSentWords.add("còn");
        vnFirstSentWords.add("tiếng");
        vnFirstSentWords.add("dòng");
        vnFirstSentWords.add("và");
        vnFirstSentWords.add("hiện");
        vnFirstSentWords.add("vợ");
        vnFirstSentWords.add("thuyền");
        vnFirstSentWords.add("vụ");
        vnFirstSentWords.add("đoàn");
        vnFirstSentWords.add("thành");
        vnFirstSentWords.add("giới");
        vnFirstSentWords.add("bến");
        vnFirstSentWords.add("vì");
        vnFirstSentWords.add("đi");
        vnFirstSentWords.add("sân");
        vnFirstSentWords.add("sâm");
        vnFirstSentWords.add("con");
        vnFirstSentWords.add("bác");
        vnFirstSentWords.add("cùng");
        vnFirstSentWords.add("báo");
        vnFirstSentWords.add("chồng");
        vnFirstSentWords.add("hàng");
        vnFirstSentWords.add("đất");
        vnFirstSentWords.add("mỗi");
        vnFirstSentWords.add("núi");
        vnFirstSentWords.add("phòng");
        vnFirstSentWords.add("xã");
        vnFirstSentWords.add("hồ");
        vnFirstSentWords.add("ông");
        vnFirstSentWords.add("giọng");
        vnFirstSentWords.add("trường");
        vnFirstSentWords.add("đèo");
        vnFirstSentWords.add("trùm");
        vnFirstSentWords.add("nhiều");
        vnFirstSentWords.add("thư");
        vnFirstSentWords.add("cục");
        vnFirstSentWords.add("nước");
        vnFirstSentWords.add("thôn");
        vnFirstSentWords.add("bạn");
        vnFirstSentWords.add("nàng");
        vnFirstSentWords.add("bệnh");
        vnFirstSentWords.add("cụm");
        vnFirstSentWords.add("tướng");
        vnFirstSentWords.add("buôn");
        vnFirstSentWords.add("để");
        vnFirstSentWords.add("anh");
        vnFirstSentWords.add("lính");
        vnFirstSentWords.add("với");
        vnFirstSentWords.add("ngoài");
        vnFirstSentWords.add("trên");
        vnFirstSentWords.add("hỏi");
        vnFirstSentWords.add("sau");
        vnFirstSentWords.add("đội");
        vnFirstSentWords.add("gọi");
        vnFirstSentWords.add("rồi");
        vnFirstSentWords.add("một");
        vnFirstSentWords.add("chúc");
        vnFirstSentWords.add("nhưng");
        vnFirstSentWords.add("đêm");
        vnFirstSentWords.add("phó");
        vnFirstSentWords.add("bỗng");
        vnFirstSentWords.add("trong");
        vnFirstSentWords.add("trước");
        vnFirstSentWords.add("bản");
        vnFirstSentWords.add("cuốn");
        vnFirstSentWords.add("chùa");
        vnFirstSentWords.add("ban");
        vnFirstSentWords.add("giữa");
        vnFirstSentWords.add("ngay");
        vnFirstSentWords.add("lúc");
        vnFirstSentWords.add("tỉnh");
        vnFirstSentWords.add("tuy");
        vnFirstSentWords.add("vẫn");

        vnFirstSentWords.add("trà");
        vnFirstSentWords.add("ôi");
        vnFirstSentWords.add("cặp");
        vnFirstSentWords.add("taxi");
        vnFirstSentWords.add("nhiễm");
        vnFirstSentWords.add("virus");
        vnFirstSentWords.add("hồi");
        vnFirstSentWords.add("nghĩa");
        vnFirstSentWords.add("đọc");
        vnFirstSentWords.add("nhờ");
        vnFirstSentWords.add("tới");
        vnFirstSentWords.add("ong");
        vnFirstSentWords.add("website");
        vnFirstSentWords.add("bóng");
        vnFirstSentWords.add("quít");
        vnFirstSentWords.add("kungfu");
        vnFirstSentWords.add("ra");
        vnFirstSentWords.add("đồng");
        vnFirstSentWords.add("băng");
        vnFirstSentWords.add("ba");
        vnFirstSentWords.add("bầu");
        vnFirstSentWords.add("hay");
        vnFirstSentWords.add("giải");
        vnFirstSentWords.add("giao");
        vnFirstSentWords.add("cửa");
        vnFirstSentWords.add("phần");
        vnFirstSentWords.add("sinh");
        vnFirstSentWords.add("vietcombank");
        vnFirstSentWords.add("vàng");
        vnFirstSentWords.add("fred");
        vnFirstSentWords.add("tập");
        vnFirstSentWords.add("toyota");
        vnFirstSentWords.add("bế");
        vnFirstSentWords.add("tuồng");
        vnFirstSentWords.add("nguồn");
        vnFirstSentWords.add("phường");
        vnFirstSentWords.add("làm");
        vnFirstSentWords.add("tuyển");
        vnFirstSentWords.add("đền");
        vnFirstSentWords.add("mong");
        vnFirstSentWords.add("nghỉ");
        vnFirstSentWords.add("hầm");
        vnFirstSentWords.add("trán");
        vnFirstSentWords.add("dắt");
        vnFirstSentWords.add("sợ");
        vnFirstSentWords.add("chỗ");
        vnFirstSentWords.add("lái");
        vnFirstSentWords.add("xem");
        vnFirstSentWords.add("chủ");
        vnFirstSentWords.add("chứ");
        vnFirstSentWords.add("đợt");
        vnFirstSentWords.add("đoạn");
        vnFirstSentWords.add("đồn");
        vnFirstSentWords.add("trục");
        vnFirstSentWords.add("tự");
        vnFirstSentWords.add("neil");
        vnFirstSentWords.add("điện");
        vnFirstSentWords.add("trạm");
        vnFirstSentWords.add("gần");
        vnFirstSentWords.add("giặc");
        vnFirstSentWords.add("cúng");
        vnFirstSentWords.add("dù");
        vnFirstSentWords.add("vịnh");
        vnFirstSentWords.add("quân");
        vnFirstSentWords.add("dãy");
        vnFirstSentWords.add("pha");
        vnFirstSentWords.add("toàn");
        vnFirstSentWords.add("tháp");
        vnFirstSentWords.add("quĩ");
        vnFirstSentWords.add("đĩa");
        vnFirstSentWords.add("gà");
        vnFirstSentWords.add("lao");
        vnFirstSentWords.add("bốn");
        vnFirstSentWords.add("họ");
        vnFirstSentWords.add("họp");
        vnFirstSentWords.add("đèn");
        vnFirstSentWords.add("cũng");
        vnFirstSentWords.add("động");
        vnFirstSentWords.add("mặt");
        vnFirstSentWords.add("đầm");
        vnFirstSentWords.add("cống");
        vnFirstSentWords.add("nơi");
        vnFirstSentWords.add("tùng");
        vnFirstSentWords.add("phố");
        vnFirstSentWords.add("đầu");
        vnFirstSentWords.add("vượt");
        vnFirstSentWords.add("sao");
        vnFirstSentWords.add("cách");
        vnFirstSentWords.add("hoặc");
        vnFirstSentWords.add("của");
        vnFirstSentWords.add("hết");
        vnFirstSentWords.add("đỉnh");
        vnFirstSentWords.add("kênh");
        vnFirstSentWords.add("quyền");
        vnFirstSentWords.add("bar");
        vnFirstSentWords.add("chống");
        vnFirstSentWords.add("khắp");
        vnFirstSentWords.add("sách");
        vnFirstSentWords.add("wikipedia");
    }

    private void initVnMiddleName() {
        vnMiddleNames = new HashSet<>();
        vnMiddleNames.add("thúy");
        vnMiddleNames.add("bao");
        vnMiddleNames.add("thùy");
        vnMiddleNames.add("mạnh");
        vnMiddleNames.add("mỹ");
        vnMiddleNames.add("an");
        vnMiddleNames.add("hoa");
        vnMiddleNames.add("nữ");
        vnMiddleNames.add("trường");
        vnMiddleNames.add("vĩnh");
        vnMiddleNames.add("đắc");
        vnMiddleNames.add("minh");
        vnMiddleNames.add("thanh");
        vnMiddleNames.add("thi");
        vnMiddleNames.add("thu");
        vnMiddleNames.add("ninh");
        vnMiddleNames.add("đình");
        vnMiddleNames.add("hải");
        vnMiddleNames.add("tuấn");
        vnMiddleNames.add("bội");
        vnMiddleNames.add("thuý");
        vnMiddleNames.add("việt");
        vnMiddleNames.add("nguyễn");
        vnMiddleNames.add("bá");
        vnMiddleNames.add("phương");
        vnMiddleNames.add("bé");
        vnMiddleNames.add("tố");
        vnMiddleNames.add("quốc");
        vnMiddleNames.add("nguyệt");
        vnMiddleNames.add("tử");
        vnMiddleNames.add("cảnh");
        vnMiddleNames.add("trọng");
        vnMiddleNames.add("huy");
        vnMiddleNames.add("nam");
        vnMiddleNames.add("chí");
        vnMiddleNames.add("thái");
        vnMiddleNames.add("thành");
        vnMiddleNames.add("chính");
        vnMiddleNames.add("đinh");
        vnMiddleNames.add("mai");
        vnMiddleNames.add("thiên");
        vnMiddleNames.add("tôn");
        vnMiddleNames.add("phi");
        vnMiddleNames.add("hà");
        vnMiddleNames.add("khắc");
        vnMiddleNames.add("trúc");
        vnMiddleNames.add("lan");
        vnMiddleNames.add("doãn");
        vnMiddleNames.add("nhất");
        vnMiddleNames.add("huỳnh");
        vnMiddleNames.add("quỳnh");
        vnMiddleNames.add("diễm");
        vnMiddleNames.add("khánh");
        vnMiddleNames.add("hữu");
        vnMiddleNames.add("tấn");
        vnMiddleNames.add("anh");
        vnMiddleNames.add("hoành");
        vnMiddleNames.add("hoàng");
        vnMiddleNames.add("diệu");
        vnMiddleNames.add("lê");
        vnMiddleNames.add("phú");
        vnMiddleNames.add("duy");
        vnMiddleNames.add("bảo");
        vnMiddleNames.add("huyền");
        vnMiddleNames.add("nguyên");
        vnMiddleNames.add("bích");
        vnMiddleNames.add("ánh");
        vnMiddleNames.add("công");
        vnMiddleNames.add("mộng");
        vnMiddleNames.add("lệnh");
        vnMiddleNames.add("cẩm");
        vnMiddleNames.add("phúc");
        vnMiddleNames.add("nhật");
        vnMiddleNames.add("ngọc");
        vnMiddleNames.add("thời");
        vnMiddleNames.add("sơn");
        vnMiddleNames.add("thuỳ");
        vnMiddleNames.add("văn");
        vnMiddleNames.add("vân");
        vnMiddleNames.add("qui");
        vnMiddleNames.add("hồng");
        vnMiddleNames.add("thế");
        vnMiddleNames.add("kim");
        vnMiddleNames.add("thị");
        vnMiddleNames.add("danh");
        vnMiddleNames.add("hoài");
        vnMiddleNames.add("tiến");
        vnMiddleNames.add("tú");
        vnMiddleNames.add("bửu");
        vnMiddleNames.add("trung");
        vnMiddleNames.add("thiện");
        vnMiddleNames.add("tuyết");
        vnMiddleNames.add("đăng");
        vnMiddleNames.add("như");
        vnMiddleNames.add("hùng");
        vnMiddleNames.add("vô");
        vnMiddleNames.add("miên");
        vnMiddleNames.add("quý");
        vnMiddleNames.add("quang");
        vnMiddleNames.add("đức");
        vnMiddleNames.add("ưng");
        vnMiddleNames.add("tường");
        vnMiddleNames.add("kiều");
        vnMiddleNames.add("thảo");
        vnMiddleNames.add("xuân");
        vnMiddleNames.add("viết");
        vnMiddleNames.add("vũ");
        vnMiddleNames.add("kế");
        vnMiddleNames.add("gia");
        vnMiddleNames.add("phước");
        vnMiddleNames.add("linh");
        vnMiddleNames.add("cao");
        vnMiddleNames.add("lệ");
    }


    private void initVnFamilyName() {
        vnFamilyNames = new HashSet<>();
        vnFamilyNames.add("bảo");
        vnFamilyNames.add("phan");
        vnFamilyNames.add("lý");
        vnFamilyNames.add("bao");
        vnFamilyNames.add("huyền");
        vnFamilyNames.add("lưu");
        vnFamilyNames.add("nguyên");
        vnFamilyNames.add("diêu");
        vnFamilyNames.add("vĩnh");
        vnFamilyNames.add("ngô");
        vnFamilyNames.add("công");
        vnFamilyNames.add("giang");
        vnFamilyNames.add("đào");
        vnFamilyNames.add("bùi");
        vnFamilyNames.add("hông");
        vnFamilyNames.add("ngọc");
        vnFamilyNames.add("chi");
        vnFamilyNames.add("bưu");
        vnFamilyNames.add("tạ");
        vnFamilyNames.add("nguyễn");
        vnFamilyNames.add("văn");
        vnFamilyNames.add("qui");
        vnFamilyNames.add("hồng");
        vnFamilyNames.add("quy");
        vnFamilyNames.add("từ");
        vnFamilyNames.add("trân");
        vnFamilyNames.add("hường");
        vnFamilyNames.add("tô");
        vnFamilyNames.add("mạc");
        vnFamilyNames.add("bửu");
        vnFamilyNames.add("đặng");
        vnFamilyNames.add("huyên");
        vnFamilyNames.add("lâm");
        vnFamilyNames.add("võ");
        vnFamilyNames.add("đinh");
        vnFamilyNames.add("miên");
        vnFamilyNames.add("mai");
        vnFamilyNames.add("hương");
        vnFamilyNames.add("lương");
        vnFamilyNames.add("hồ");
        vnFamilyNames.add("tôn");
        vnFamilyNames.add("ưng");
        vnFamilyNames.add("la");
        vnFamilyNames.add("thân");
        vnFamilyNames.add("hà");
        vnFamilyNames.add("dương");
        vnFamilyNames.add("trịnh");
        vnFamilyNames.add("tằng");
        vnFamilyNames.add("lan");
        vnFamilyNames.add("doãn");
        vnFamilyNames.add("vinh");
        vnFamilyNames.add("trần");
        vnFamilyNames.add("huỳnh");
        vnFamilyNames.add("vương");
        vnFamilyNames.add("vũ");
        vnFamilyNames.add("cao");
        vnFamilyNames.add("phạm");
        vnFamilyNames.add("hoàng");
        vnFamilyNames.add("đỗ");
        vnFamilyNames.add("trương");
        vnFamilyNames.add("đoàn");
        vnFamilyNames.add("diệp");
        vnFamilyNames.add("lê");
    }
}